# Year the survey was administered. Could be useful for creating 
# longitudinal reshaped data
year: 2013

# How you want the survey referred to in the output file. You 
# generally won't want to include the year here since if you're 
# ever doing logitudinal analysis, you'll want to be able to identify
# two surveys from different years as the same survey
survey_name: 'Senior Survey One Year Out'

# Name of weight column in input data file(s). If you have no weight
# column in your input data file, make up a value here such as 'weight' 
# or 'wt'. This column will be created in the output file with all 
# values set to 1.
weight_col: 'wt'

# Paths to 3 different input files, in order: data, question to text map,
# and value to label map. The format for all the 3 files have to be in xlsx.
input_filename_with_values: 'Original/Senior_Survey_May_2013 Excel to CSV with Values.xlsx'
input_filename_questions_to_text: 'Original/Senior Survey 2013 Questions to Text.xlsx'
input_filename_values_to_labels: 'Original/Senior Survey 2013 Values to Labels.xlsx'

# These are ID of attributes in the input file that you want to 
# treat as questions in the output file. They are generally 
# metadata, or things you want to analyze the survey by. You don't
# need to include your weight columns here, since they'll
# automatically be included.
both_attribute_and_question: [
    'V1',
    'V2'
]

# These are columns that you want to completely ignore from your data,
# so these columns will not show up in the output file. Make sure to 
# use the columns' name in the original input file, not its textual 
# name.
columns_to_ignore: [
  'LocationAccuracy',
  'LocationLongitude',
  'LocationLatitude',
  'V6'
]

# Determine the minimum length of the common substring when determining 
# the question group text
common_string_threshold: 4

# This is a list of the text responses (not case-sensitive) that will be 
# excluded from the domain analysis, as sometimes NA answers will be 
# assigned a value. This will allow the domain computation to be performed 
# more correctly.
exclude_from_domain_analysis: ['Not applicable', 'NA', 'Not a response']